twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: ['bootstrap_4_layout.html.twig']
  globals:
    copyright: "Anas-Emmanuel FAOUR Décembre-2019 © Tous droits réservés"
    maintitle: "User Stories"